### ISSUE TITLE
Auto-read `code` response from the browser (no more dialogs)

### ISSUE THREAD

**Issue by cmin764** [robocorp/example-oauth-email#5]
People have no idea that they should copy the respone URL from the address bar into the dialog that waits for it and also people don't read documentation, so, to simplify it:
1. As soon as the auth URL is opened in the browser, the robot waits for the code response by reading the content from the address bar.
2. Once the final response is detected, then that is captured and passed further to the token retrieval keyword. (so no more dialogs are involved)

If by any reason the auth cannot be completed in the opened browser, the auth URL can be opened in your own browser and from there you complete the flow by copy-pasting the obtained response URL back into the originally opened tab window.

### ToDos
- [x] Steps described above.
- [x] README updates + @tonnitommi suggestions: https://github.com/robocorp/example-oauth-email/issues/4
- [x] More on README
  - Reordering the section with "Google consent screen config" + "API enablement".
  - "How to create Microsoft Client app credentials" section.
  - Screenshot for the alternative of copy-paste of the response code back in the opened browser window. (if auth problems encountered along the way)
    - Even better, trying **undetected-chromedriver** for patching `Chrome` webdriver in such a way the auth is allowed from the automated browser. (check behaviour with `use_profile=${True}` as well)
  - Loom videos with configuration and steps running in order to get and use the token to send an e-mail to yourself. (optional run from Control Room)
